[package]
name = "vm"
version = "0.1.0"
authors = ["Andrei Pago <andpago@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-primitive-derive = "0.1.2"
num-traits = "0.2.8"
cortex-m-semihosting = "*"